name: Build

on:
  push:
    branches: 
      - master
    paths:
      - 'sabatex.Identity.UI/sabatex.Identity.UI.csproj'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
           dotnet-version: 6.0.x
           source-url: https://nuget.pkg.github.com/sabatex/index.json
        env:
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: build
        run: dotnet build sabatex.Identity.UI/sabatex.Identity.UI.csproj
